// This command allows the bot to randomly choose a Brawl Stars Character and display their information
module.exports = {
    name: 'chbrawler',
    description: "idk aun",
    async execute(message, args, cmd, client, Discord) {

        const shelly = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('SHELLY')
            .setDescription('**Descripción:** Shelly`s spread-fire shotgun blasts the other team with buckshot.\nHer Super destroys cover and keeps her opponents at a distance!')
            .setImage('https://cdn.brawlify.com/skin/Star-Shelly.png?v=1')

        const nita = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setTitle('NITA')
            .setColor('#0ebcfb')
            .setDescription('**Descripción:** Nita strikes her enemies with a thunderous shockwave.\nHer Super summons a massive bear to fight by her side!')
            .setImage('https://cdn.brawlify.com/skin/Shiba-Nita.png?v=1')

        const colt = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('COLT')
            .setDescription('**Descripción:** Colt fires an accurate burst of bullets from his dual revolvers.\nHis Super shreds cover and extends the bullet barrage!')
            .setImage('https://cdn.brawlify.com/skin/Outlaw-Colt.png?v=1')

        const bull = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('BULL')
            .setDescription('**Descripción:** Bull deals massive damage up close with his shotgun.\nFor his Super move, he charges through barriers and knocks back enemies!')
            .setImage('https://cdn.brawlify.com/skin/Linebacker-Bull.png')

        const jessie = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('JESSIE')
            .setDescription('**Descripción:** Jessie`s Shock Rifle shoots energy orbs that bounce between enemies.\nHer Super deploys a cute but deadly gun turret!')
            .setImage('https://cdn.brawlify.com/skin/Dragon-King-Jessie.png')

        const brock = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('BROCK')
            .setDescription('**Descripción:** Brock fires a long-range, explosive rocket at enemies.\nHis Super is a ballistic rocket barrage that destroys cover!')
            .setImage('https://cdn.brawlify.com/skin/Beach-Brock.png')

        const dyna = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('DYNAMIKE')
            .setDescription('**Descripción:** Dynamike lobs two explosive sticks of dynamite.\nHis Super attack is a whole barrel full of dynamite that blows up cover!')
            .setImage('https://cdn.brawlify.com/skin/Spicy-Mike.png')

        const bo = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('BO')
            .setDescription('**Descripción:** Bo fires three explosive arrows toward his targets.\nHis Super ability places a trio of hidden, explosive mines on the ground!')
            .setImage('https://cdn.brawlify.com/skin/Light-Mecha-Bo.png')

        const tick = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('TICK')
            .setDescription('**Descripción:** Tick is a metal ball of barely controlled excitement and energy - explosive energy!\nHe throws mines, and his Super makes his head detach, seek a target and explode.')
            .setImage('https://cdn.brawlify.com/skin/King-Crab-Tick.png')

        const bit = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('8-BIT')
            .setDescription('**Descripción:** 8-Bit lumbers along like an arcade cabinet on legs.\nHe shoots Blaster Beams and his Super boosts friendlies` damage!')
            .setImage('https://cdn.brawlify.com/skin/Virus-8-Bit.png')

        const emz = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('EMZ')
            .setDescription('**Descripción:** Emz attacks with blasts of hair spray that deal damage over time,\nand slows down opponents with her Super.')
            .setImage('https://cdn.brawlify.com/skin/College-EMZ.png')

        const stu = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('STU')
            .setDescription('**Descripción:** Stu is a stunt driver extraordinaire with gasoline in his veins!\nHe makes a big entrance, burning serious rubber all over the stage.')
            .setImage('https://www.chillbs.com/core/uploads/2021/03/Stu-Superstar.png')

        const primo = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('EL PRIMO')
            .setDescription('**Descripción:** El Primo throws a flurry of punches at his enemies.\nHis Super is a leaping elbow drop that deals damage to all caught underneath!')
            .setImage('https://cdn.brawlify.com/skin/El-Rey-Primo.png')

        const barley = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('BARLEY')
            .setDescription('**Descripción:** Barley attacks by lobbing bottles at enemies, doing splash damage.\nHis Super is a huge barrage of burning bottles!')
            .setImage('https://cdn.brawlify.com/skin/Wizard-Barley.png')

        const poco = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('POCO')
            .setDescription('**Descripción:** Poco fires damaging sound waves at enemies.\nHis Super can heal both Poco himself and his teammates!')
            .setImage('https://cdn.brawlify.com/skin/Serenade-Poco.png')

        const rosa = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('ROSA')
            .setDescription('**Descripción:** This boxing botanist will plant her feet and go toe to toe!\nHer Super gives her tough, vegan protective gear.')
            .setImage('https://www.chillbs.com/core/uploads/2020/03/rosa-brawl-stars.png')

        const rico = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('RICOCHET')
            .setDescription('**Descripción:** Rico fires a burst of bullets that bounce off walls.\nHis Super burst is a long barrage of bouncy bullets that pierce targets!')
            .setImage('https://cdn.brawlify.com/skin/Classic-Rico.png')

        const darryl = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('DARRYL')
            .setDescription('**Descripción:** Darryl has a powerful double-shotgun attack.\nHis Super move is a reckless roll inside his bouncy barrel!')
            .setImage('https://cdn.brawlify.com/skin/Dumpling-Darryl.png')

        const penny = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('PENNY')
            .setDescription('**Descripción:** Penny shoots bags of coins,\ndamaging the target and anyone standing behind.\nHer Super is a mortar-style cannon turret!')
            .setImage('https://cdn.brawlify.com/skin/Bunny-Penny.png')

        const carl = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('CARL')
            .setDescription('**Descripción:** Carl throws his Pickaxe like a boomerang.\nHis Super is a crazy cart spin that clobbers anyone around him.')
            .setImage('https://cdn.brawlify.com/skin/Hog-Rider-Carl.png')

        const jacky = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('JACKY')
            .setDescription('**Descripción:** Jacky works her Jackhammer to shake up the ground and nearby enemies.\nHer Super pulls in nearby foes, leaving them in the dust!')
            .setImage('https://cdn.brawlify.com/skin/Constructor-Jacky.png')

        const piper = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('PIPER')
            .setDescription('**Descripción:** Piper`s sniper shots do more damage the farther they travel.\nHer Super drops grenades at her feet, while Piper herself leaps away!')
            .setImage('https://cdn.brawlify.com/skin/Cupid-Piper.png')

        const pam = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('PAM')
            .setDescription('**Descripción:** Pam shoots from the hip, peppering targets with shrapnel.\nHer Super is a healing turret that restores her and teammates` health!')
            .setImage('https://cdn.brawlify.com/skin/Holiday-Pam.png')

        const frank = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('FRANK')
            .setDescription('**Descripción:** Frank swings his hammer at enemies, sending a shockwave.\nHis Super is an especially powerful blow that stuns enemies!')
            .setImage('https://cdn.brawlify.com/skin/DJ-Frank.png')

        const bibi = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('BIBI')
            .setDescription('**Descripción:** Batter up! Bibi`s got a sweet swing that can knock back enemies when her Home Run bar is charged.\nHer Super is a bouncing ball of gum that deals damage.')
            .setImage('https://cdn.brawlify.com/skin/Heroine-Bibi.png')

        const bea = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('BEA')
            .setDescription('**Descripción:** Bea loves bugs and hugs.\nShe shoots her mechanical drones at range, and\nher Super sends forth an angry army of swarming bees!')
            .setImage('https://cdn.brawlify.com/skin/Ladybug-Bea.png')

        const nani = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('NANI')
            .setDescription('**Descripción:** Nani loves her friends and looks over them with a watchful lens.\nShe handles threats with angled shots, and\nher Super allows Nani to commandeer her pal Peep, who goes out with a bang!')
            .setImage('https://cdn.brawlify.com/skin/Retro-Nani.png')

        const edgar = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('EDGAR')
            .setDescription('**Descripción:** Let`s face it, this is an angry kid. He also loves parkour.')
            .setImage('https://cdn.brawlify.com/skin/Retro-Nani.png')

        const griff = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('GRIFF')
            .setDescription('**Descripción:** Griffo is the proprietor of Starr Park`s gift shop. \nBusiness is bad, but he still throws coins away - from his employees` tip jar!')
            .setImage('https://static.wikia.nocookie.net/brawlstars/images/0/0f/Griff_Skin-Default.png/revision/latest?cb=20210616182427')

        const mortis = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('MORTIS')
            .setDescription('**Descripción:** Mortis dashes forward with each swing of his shovel.\nAs his Super attack, he sends a cloud of bats to damage enemies and heal himself!')
            .setImage('https://cdn.brawlify.com/skin/Rockability-Mortis.png')

        const tara = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('TARA')
            .setDescription('**Descripción:** Tara`s triple tarot card attack pierces through enemies.\nHer Super is a black hole that sucks in all nearby enemies,\ncausing damage!')
            .setImage('https://cdn.brawlify.com/skin/Iris-Tara.png')

        const gene = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('GENE')
            .setDescription('**Descripción:** Gene uses his magic lamp to shoot a splitting projectile.\nHis super is a magical hand that grabs and pulls enemies close!')
            .setImage('https://cdn.brawlify.com/skin/Pirate-Gene.png')

        const max = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('MAX')
            .setDescription('**Descripción:** Maximiliano goes fast! Her attack is a fast-firing blaster.\nHer Super speeds up her and allies!')
            .setImage('https://cdn.brawlify.com/skin/Streetwear-Max.png')

        const mrp = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('MR. P')
            .setDescription('**Descripción:** Mr. P is a disgruntled luggage handler who angrily hurls suitcases at opponents.\nHis Super calls robo-porters to help him.')
            .setImage('https://cdn.brawlify.com/skin/Agent-P.png')

        const sprout = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('SPROUT')
            .setDescription('**Descripción:** Sprout was built to plant life,\nlaunching bouncy Seed Bombs with reckless love.\nIts Super creates a plant-based obstacle!')
            .setImage('https://cdn.brawlify.com/skin/Tropical-Sprout.png')

        const byron = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('BYRON')
            .setDescription('**Descripción:** Byron deals with potent medicaments,\nbut never call him a snake oil salesman!')
            .setImage('https://www.chillbs.com/core/uploads/2020/12/byron.png')

        const squeak = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('SQUEAK')
            .setDescription('**Descripción:** As Col. Ruff´s accidental creation,\nSqueak was born to play fetch!')
            .setImage('https://www.chillbs.com/core/uploads/2021/05/squeak.png')

        const spike = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('SPIKE')
            .setDescription('**Descripción:** Spike throws cactus grenades that send needles flying,\nand a show-stopping Super:\na field of cactus spines that slows down and damages enemies!')
            .setImage('https://pm1.narvii.com/7820/e18c24edf5ba4bdb8d6bcd6fdc1810ecb1c2fa3dr1-1200-1200v2_hq.jpg')

        const crow = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('CROW')
            .setDescription('**Descripción:** Crow fires a trio of poisoned daggers.\nAs a Super move he leaps,\nfiring daggers both on jump and on landing!')
            .setImage('https://dthezntil550i.cloudfront.net/rx/latest/rx1902260446116890008222184/1280_960/28413eb7-17e8-41a6-89db-027f56191b20.png')

        const leon = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('LEON')
            .setDescription('**Descripción:** Leon shoots a quick salvo of blades at his target.\nHis Super trick is a smoke bomb that makes him invisible for a little while!')
            .setImage('https://images-na.ssl-images-amazon.com/images/I/61zmR6TdWfL._AC_SL1200_.jpg')

        const sandy = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('SANDY')
            .setDescription('**Descripción:** Sandy is a sleep-deprived Brawler with powerful control over sand:\ncasting sharp pebbles at enemies, and summoning a sandstorm to hide teammates.')
            .setImage('https://studio.cults3d.com/Yc-LLnmrXJI-e_n3nVeNXEG2C4Y=/https://files.cults3d.com/uploaders/14390904/illustration-file/627c3992-eb4d-4bdb-93cc-5fd12f02f3e4/Sandy1.jpg')

        const amber = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('AMBER')
            .setDescription('**Descripción:** Amber has always been a firebug.\nShe loves to light up the world and any opponents that come at her!')
            .setImage('https://pbs.twimg.com/media/ElFlHBKXUAUpSmD.jpg:large')

        const meg = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('MEG')
            .setDescription('**Descripción:** Meg has a basic form and an advanced form where she hops inside her trusted Mecha. \nThe Mecha loses health over time and has low healing ability. \nDestroying the Mecha returns Meg to her basic form.')
            .setImage('https://cdn1.dotesports.com/wp-content/uploads/2021/09/25131214/brawler.png')

        const gale = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('GALE')
            .setDescription('**Descripción:** Gale is a tireless handyman who gets no rest.\nHe blasts foes with a wide shot of wind and snow and\nhis Super pushes them back with a huge gust of wind!')
            .setImage('https://cdn.brawlify.com/skin/Trader-Gale.png')

        const surge = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('SURGE')
            .setDescription('**Descripción:** He`s a Protector with a penchant for parties.\nSurge attacks foes with energy drink blasts that split in two on contact.\nHis Super upgrades his stats in 3 stages and comes complete with totally awesome body mods!')
            .setImage('https://cdn.brawlify.com/skin/Mecha-Paladin-Surge.png')

        const colette = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('COLETTE')
            .setDescription('**Descripción:** Colette is going to get you!\nShe taxes opponents` health and has fancy moves to boot.')
            .setImage('https://www.chillbs.com/core/uploads/2020/09/trixie-colette-skin.png')

        const lou = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('LOU')
            .setDescription('**Descripción:** Lou is a cool guy, literally!\nHe can dole out all kinds of chill stuff.\nBut watch your step on the ice,\nand be careful not to get brain freeze!')
            .setImage('https://img.game8.co/3347401/c35497d3de4a7d4b197121fa4beee7c4.png/show')

        const ruffs = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('RUFFS')
            .setDescription('**Descripción:** Ruffs fires twin shots of lasers that bounce off walls.\nHis Super is a supply drop that can damage enemies in the drop zone\nand leaves a power up for your team to use.')
            .setImage('https://owwya.com/wp-content/uploads/2021/02/Brawl-Stars-Ronin-Ruffs-Skin.png')

        const belle = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('BELLE')
            .setDescription('**Descripción:** Belle inspires adoration in her gang,\nwhile her Electo-Rifle brings shock and awe to any opponent!')
            .setImage('https://brawl-stars.info/wp-content/uploads/2021/04/3F3F3F3F3F_3F3F3F3F3F3F3F3F.png')

        const buzz = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('BUZZ')
            .setDescription('**Descripción:** Buzz is the lifeguard at Velocirapids.\nHe constantly scans for folks in trouble he can throw his torpedo buoy to,\nbut his throws are rather overenthusiastic.')
            .setImage('https://i.redd.it/pbimcjbm37571.png')

        const ash = new Discord.MessageEmbed()
            .setAuthor('Mi selección para tí es...')
            .setColor('#0ebcfb')
            .setTitle('ASH')
            .setDescription('**Descripción:** Ash easily gets furious about all the junk he has to clean up. \nDealing or receiving blows, even more so. \nThe Fury makes him faster and more dangerous, but eventually he cools down.')
            .setImage('https://i.pinimg.com/originals/28/ec/d6/28ecd67d058708db6a65de3e88f2c9f6.png')

        const brawlersEmbeds = [shelly, nita, colt, bull, jessie, brock, dyna, bo, tick, bit, emz, stu, primo, barley, poco, rosa, rico,
            darryl, penny, carl, jacky, piper, pam, frank, bibi, bea, nani, edgar, griff, mortis, tara, gene, max, mrp, sprout, byron, squeak,
            spike, crow, leon, sandy, amber, meg, gale, surge, colette, lou, ruffs, belle, buzz, ash]

        const randomMessage = brawlersEmbeds[Math.floor(Math.random() * brawlersEmbeds.length)];

        message.channel.send(randomMessage).then((sent) => {
            setTimeout(function () {
                sent.delete();
                message.delete();
            }, 600000);
        });
    }
}
